// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	todo "micro-todo/service/todo/api/internal/handler/todo"
	"micro-todo/service/todo/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: todo.CreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/:id",
					Handler: todo.PartialUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: todo.UpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/done/:id",
					Handler: todo.DoneHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/done",
					Handler: todo.BatchDoneHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: todo.GetTodoListHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: todo.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/",
					Handler: todo.BatchDeleteHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/todo"),
	)
}
