// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"micro-todo/service/user/rpc/internal/logic"
	"micro-todo/service/user/rpc/internal/svc"
	"micro-todo/service/user/rpc/types/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Auth(ctx context.Context, in *user.AuthReq) (*user.AuthReply, error) {
	l := logic.NewAuthLogic(ctx, s.svcCtx)
	return l.Auth(in)
}
