// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package user

import (
	"context"

	"micro-todo/service/user/rpc/types/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuthReply = user.AuthReply
	AuthReq   = user.AuthReq

	User interface {
		Auth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthReply, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Auth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthReply, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Auth(ctx, in, opts...)
}
