// Code generated by goctl. DO NOT EDIT.
package types

type CreateReq struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type PartialUpdateReq struct {
	Id      int64  `path:"id"`
	Title   string `json:"title,optional"`
	Content string `json:"content,optional"`
}

type UpdateReq struct {
	Id      int64  `path:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type DoneReq struct {
	Id    int64 `path:"id"`
	State bool  `form:"state,optional,default=true"`
}

type BatchDoneReq struct {
	State bool `form:"state"`
}

type GetTodoListReq struct {
	Type       string `form:"tp,optional,options=all|done|todo,default=all"`
	KeyWorld   string `form:"kw,optional,default="`
	PageNumber int    `form:"pn,optional,default=1"`
	PageSize   int    `form:"ps,optional,default=20,range=[1:100]"`
}

type TodoReply struct {
	Id      int64  `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
	Done    bool   `json:"done"`
}

type GetTodoListReply struct {
	Count    int         `json:"count"`
	TodoList []TodoReply `json:"todolist"`
}

type DeleteReq struct {
	Id int64 `path:"id"`
}

type BatchDeleteReq struct {
	Type string `form:"tp,options=all|done|todo"`
}
